"use client"
import { useState, useMemo } from "react"
import { Button } from "@/components/ui/button"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { Input } from "@/components/ui/input"
import { Search } from "lucide-react"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

interface EmojiPickerProps {
  value: string
  onChange: (emoji: string) => void
  inline?: boolean
}

const EMOJI_NAMES: Record<string, string> = {
  // Smileys
  "😀": "grinning face smile happy",
  "😃": "grinning face smile happy joy",
  "😄": "grinning face smile happy joy laugh",
  "😁": "beaming face smile happy grin",
  "😆": "laughing face smile happy lol",
  "😅": "sweat smile nervous laugh",
  "😂": "joy tears laugh crying funny lol",
  "🤣": "rolling laugh floor funny lol rofl",
  "😊": "smile blush happy pleased",
  "😇": "angel halo innocent smile",
  "🙂": "smile slight happy",
  "🙃": "upside down smile sarcastic",
  "😉": "wink flirt smile",
  "😌": "relieved smile peaceful calm",
  "😍": "heart eyes love adore",
  "🥰": "smiling hearts love adore",
  "😘": "kiss love heart",
  "😗": "kiss smile",
  "😙": "kiss smile",
  "😚": "kiss smile closed eyes",
  "😋": "yum delicious food tasty hungry eating",
  "😛": "tongue out playful",
  "😝": "tongue wink playful",
  "😜": "tongue wink playful",
  "🤪": "zany crazy wild silly",
  "🤨": "raised eyebrow skeptical suspicious",
  "🧐": "monocle thinking curious",
  "🤓": "nerd glasses geek smart",
  "😎": "cool sunglasses awesome",
  "🤩": "star struck amazed wow",
  "🥳": "party celebrate birthday",
  "😏": "smirk sly confident",
  "😒": "unamused annoyed bored",
  "😞": "disappointed sad unhappy",
  "😔": "pensive sad thoughtful",
  "😟": "worried anxious concerned",
  "😕": "confused puzzled uncertain",
  "🙁": "frown sad unhappy",
  "☹️": "frown sad unhappy",
  "😣": "persevere struggle difficult",
  "😖": "confounded frustrated upset",
  "😫": "tired exhausted weary",
  "😩": "weary tired exhausted",
  "🥺": "pleading puppy eyes sad",
  "😢": "cry sad tears",
  "😭": "crying tears sob sad",
  "😤": "triumph proud steam",
  "😠": "angry mad upset",
  "😡": "rage angry furious mad",
  "🤬": "cursing swearing angry symbols",
  "🤯": "mind blown exploding shocked",
  "😳": "flushed embarrassed surprised",
  "🥵": "hot sweat heat",
  "🥶": "cold freezing ice",
  "😱": "scream fear scared shocked",
  "😨": "fearful scared afraid",
  "😰": "anxious nervous worried sweat",
  "😥": "sad sweat disappointed",
  "😓": "downcast sweat tired",
  "🤗": "hugging hug embrace",
  "🤔": "thinking hmm consider",
  "🤭": "hand over mouth oops giggle",
  "🤫": "shush quiet silence",
  "🤥": "lying pinocchio nose",
  "🤠": "cowboy hat western yeehaw",
  "👹": "ogre monster demon red",
  "👺": "goblin monster tengu",
  "👽": "alien extraterrestrial ufo space",
  "👾": "alien monster space invader game",
  "🤖": "robot machine ai artificial intelligence",
  "👻": "ghost spooky halloween boo",
  "😈": "devil smiling evil mischief",
  "👿": "devil angry evil imp",
  "💀": "skull death dead skeleton bones",
  "☠️": "skull crossbones death danger poison",
  "🎃": "jack-o-lantern halloween pumpkin",
  "😺": "cat grinning smile happy",
  "😸": "cat grin smile happy",
  "😹": "cat joy tears laugh",
  "😻": "cat heart eyes love",
  "😼": "cat wry smile smirk",
  "😽": "cat kiss",
  "🙀": "cat weary shocked",
  "😿": "cat crying sad tears",
  "😾": "cat pouting upset",
  "👀": "eyes looking watching see vision",
  "👁️": "eye looking watching see vision",
  "👓": "glasses eyeglasses spectacles vision reading",
  "🕶️": "sunglasses cool shades dark glasses",
  "🥽": "goggles safety swimming diving protection",

  // Hearts & Symbols
  "❤️": "red heart love romance passion",
  "🧡": "orange heart love warm",
  "💛": "yellow heart love friendship happy",
  "💚": "green heart love nature jealous",
  "💙": "blue heart love trust calm",
  "💜": "purple heart love royal",
  "🖤": "black heart love dark gothic",
  "🤍": "white heart love pure clean",
  "🤎": "brown heart love earth",
  "💔": "broken heart sad heartbreak pain",
  "❣️": "heart exclamation love emphasis",
  "💕": "two hearts love romance",
  "💞": "revolving hearts love romance",
  "💓": "beating heart love pulse alive",
  "💗": "growing heart love increasing",
  "💖": "sparkling heart love shine",
  "💘": "heart arrow cupid love struck",
  "💝": "heart ribbon gift love present",
  "💟": "heart decoration love ornament",
  "❤️‍🔥": "heart fire love passion burning",
  "❤️‍🩹": "mending heart healing recovery love",
  "✅": "check mark done complete yes correct approved task finished",
  "☑️": "checkbox checked done complete yes correct approved task finished ballot",
  "✔️": "check mark done complete yes correct approved heavy",
  "❌": "cross mark no wrong incorrect cancel delete remove error",
  "❎": "cross mark button no wrong incorrect cancel",
  "✖️": "multiplication sign cross cancel delete remove times",
  "❓": "question mark help unknown confused inquiry ask what why how",
  "❔": "question mark white help unknown",
  "❗": "exclamation mark important alert warning attention urgent",
  "❕": "exclamation mark white important alert",
  "‼️": "double exclamation important very urgent",
  "⁉️": "exclamation question surprised important",
  "⭕": "hollow circle correct ring zero",
  "🔴": "red circle dot stop color",
  "🟠": "orange circle dot color",
  "🟡": "yellow circle dot color caution",
  "🟢": "green circle dot go color",
  "🔵": "blue circle dot color",
  "🟣": "purple circle dot color",
  "🟤": "brown circle dot color",
  "⚫": "black circle dot color",
  "⚪": "white circle dot color",
  "🔺": "red triangle pointed up arrow",
  "🔻": "red triangle pointed down arrow",
  "🔶": "orange diamond shape large",
  "🔷": "blue diamond shape large",
  "🔸": "orange diamond shape small",
  "🔹": "blue diamond shape small",
  "🟥": "red square shape color",
  "🟧": "orange square shape color",
  "🟨": "yellow square shape color",
  "🟩": "green square shape color",
  "🟦": "blue square shape color",
  "🟪": "purple square shape color",
  "🟫": "brown square shape color",
  "⬛": "black square shape color",
  "⬜": "white square shape color",
  "⭐": "star yellow rating favorite",
  "🌟": "glowing star shine bright sparkle",
  "✨": "sparkles shine magic glitter stars",
  "💫": "dizzy star circle spin",
  "🌈": "rainbow colors arc pride",
  "☀️": "sun sunny bright day weather",
  "🌙": "crescent moon night sleep",
  "⚡": "high voltage lightning electricity power energy fast",
  "🔥": "fire hot flame burn lit",
  "💧": "droplet water tear rain",
  "🌊": "wave water ocean sea surf",
  "💬": "speech bubble talk chat comment message discuss conversation",
  "🗨️": "speech bubble left talk chat comment",
  "🗯️": "anger bubble right mad yell shout",
  "💭": "thought bubble think idea dream imagine",
  "🗣️": "speaking head talk say voice speech person face announce",
  "👄": "mouth lips talk kiss speak",
  "👅": "tongue lick taste",

  // People
  "👶": "baby infant child",
  "🧒": "child kid young",
  "👦": "boy child kid",
  "👧": "girl child kid",
  "🧑": "person adult human",
  "👱": "person blonde hair",
  "👨": "man male adult",
  "🧔": "man beard facial hair",
  "👩": "woman female adult",
  "🧓": "older person elderly senior",
  "👴": "old man elderly grandfather",
  "👵": "old woman elderly grandmother",
  "💃": "woman dancing dance party celebration",
  "🕺": "man dancing dance party celebration",
  "👨‍⚕️": "man doctor health medical physician",
  "👩‍⚕️": "woman doctor health medical physician",
  "🧑‍⚕️": "person doctor health medical physician",
  "👨‍🎓": "man student graduate education",
  "👩‍🎓": "woman student graduate education",
  "🧑‍🎓": "person student graduate education",
  "👨‍🏫": "man teacher professor education instructor",
  "👩‍🏫": "woman teacher professor education instructor",
  "🧑‍🏫": "person teacher professor education instructor",
  "👨‍⚖️": "man judge law court justice",
  "👩‍⚖️": "woman judge law court justice",
  "🧑‍⚖️": "person judge law court justice",
  "👨‍🌾": "man farmer agriculture farming",
  "👩‍🌾": "woman farmer agriculture farming",
  "🧑‍🌾": "person farmer agriculture farming",
  "👨‍🍳": "man cook chef cooking kitchen",
  "👩‍🍳": "woman cook chef cooking kitchen",
  "🧑‍🍳": "person cook chef cooking kitchen",
  "👨‍🔧": "man mechanic repair technician",
  "👩‍🔧": "woman mechanic repair technician",
  "🧑‍🔧": "person mechanic repair technician",
  "👨‍🏭": "man factory worker industrial",
  "👩‍🏭": "woman factory worker industrial",
  "🧑‍🏭": "person factory worker industrial",
  "👨‍💼": "man office worker business professional",
  "👩‍💼": "woman office worker business professional",
  "🧑‍💼": "person office worker business professional",
  "👨‍🔬": "man scientist research lab",
  "👩‍🔬": "woman scientist research lab",
  "🧑‍🔬": "person scientist research lab",
  "👨‍💻": "man technologist programmer developer coder",
  "👩‍💻": "woman technologist programmer developer coder",
  "🧑‍💻": "person technologist programmer developer coder",
  "👨‍🎤": "man singer musician performer artist",
  "👩‍🎤": "woman singer musician performer artist",
  "🧑‍🎤": "person singer musician performer artist",
  "👨‍🎨": "man artist painter creative",
  "👩‍🎨": "woman artist painter creative",
  "🧑‍🎨": "person artist painter creative",
  "👨‍✈️": "man pilot aviation airplane",
  "👩‍✈️": "woman pilot aviation airplane",
  "🧑‍✈️": "person pilot aviation airplane",
  "👨‍🚀": "man astronaut space rocket",
  "👩‍🚀": "woman astronaut space rocket",
  "🧑‍🚀": "person astronaut space rocket",
  "👨‍🚒": "man firefighter fire emergency",
  "👩‍🚒": "woman firefighter fire emergency",
  "🧑‍🚒": "person firefighter fire emergency",
  "👮": "police officer cop law enforcement",
  "🕵️": "detective spy investigator",
  "💂": "guard soldier",
  "👷": "construction worker builder",
  "🤴": "prince royal",
  "👸": "princess royal",
  "👳": "person turban",
  "👲": "person skullcap",
  "🧕": "person headscarf",
  "🤵": "person tuxedo",
  "👰": "person veil bride",
  "🤰": "pregnant woman",
  "🤱": "breast feeding",
  "👼": "baby angel",
  "🎅": "santa claus christmas",
  "🤶": "mrs claus christmas",
  "🦸": "superhero hero",
  "🦹": "supervillain villain",
  "🧙": "mage wizard",
  "🧚": "fairy magic",
  "🧛": "vampire",
  "🧜": "merperson mermaid",
  "🧝": "elf",
  "🧞": "genie",
  "🧟": "zombie",
  "💆": "person massage spa",

  // Animals
  "🐶": "dog puppy pet animal",
  "🐱": "cat kitten pet animal",
  "🐭": "mouse rat animal",
  "🐹": "hamster pet animal",
  "🐰": "rabbit bunny animal",
  "🦊": "fox animal",
  "🐻": "bear animal",
  "🐼": "panda bear animal",
  "🐨": "koala bear animal",
  "🐯": "tiger animal",
  "🦁": "lion animal king",
  "🐮": "cow animal farm",
  "🐷": "pig animal farm",
  "🐽": "pig nose snout",
  "🐸": "frog animal",
  "🐵": "monkey animal",
  "🙈": "see no evil monkey",
  "🙉": "hear no evil monkey",
  "🙊": "speak no evil monkey",
  "🐒": "monkey animal",
  "🐔": "chicken rooster bird farm",
  "🐧": "penguin bird animal",
  "🐦": "bird animal",
  "🐤": "baby chick bird",
  "🐣": "hatching chick bird egg",
  "🐥": "baby chick bird",
  "🦆": "duck bird animal",
  "🦅": "eagle bird animal",
  "🦉": "owl bird animal night",
  "🦇": "bat animal night",
  "🐺": "wolf animal",
  "🐗": "boar pig animal",
  "🐴": "horse animal",
  "🦄": "unicorn horse magical",
  "🐝": "bee insect honey",
  "🐛": "bug caterpillar insect",
  "🦋": "butterfly insect",
  "🐌": "snail slow animal",
  "🐞": "ladybug insect",
  "🐜": "ant insect",
  "🦟": "mosquito insect",
  "🦗": "cricket insect",
  "🕷️": "spider insect",
  "🦂": "scorpion insect",
  "🐢": "turtle animal",
  "🐍": "snake animal",
  "🦎": "lizard animal",
  "🦖": "dinosaur animal",

  // Food
  "🍎": "apple fruit red food",
  "🍐": "pear fruit food",
  "🍊": "orange fruit food citrus",
  "🍋": "lemon fruit food citrus sour",
  "🍌": "banana fruit food yellow",
  "🍉": "watermelon fruit food summer",
  "🍇": "grapes fruit food purple",
  "🍓": "strawberry fruit food red berry",
  "🍈": "melon fruit food",
  "🍒": "cherries fruit food red",
  "🍑": "peach fruit food",
  "🥭": "mango fruit food tropical",
  "🍍": "pineapple fruit food tropical",
  "🥥": "coconut fruit food tropical",
  "🥝": "kiwi fruit food green",
  "🍅": "tomato vegetable food red",
  "🍆": "eggplant vegetable food purple",
  "🥑": "avocado fruit food green",
  "🥦": "broccoli vegetable food green",
  "🥒": "cucumber vegetable food green",
  "🌶️": "pepper hot spicy food",
  "🌽": "corn vegetable food yellow",
  "🥕": "carrot vegetable food orange",
  "🥔": "potato vegetable food",
  "🍠": "sweet potato vegetable food",
  "🥐": "croissant bread food pastry",
  "🥖": "baguette bread food french",
  "🍞": "bread food loaf",
  "🧀": "cheese food dairy",
  "🥚": "egg food breakfast",
  "🍳": "cooking egg food breakfast",
  "🥞": "pancakes food breakfast",
  "🥓": "bacon food breakfast meat",
  "🥩": "meat steak food",
  "🍗": "chicken leg food meat",
  "🍖": "meat bone food",
  "🌭": "hot dog food",
  "☕": "coffee hot drink beverage morning cafe",
  "🍵": "tea hot drink beverage green",
  "🍺": "beer drink alcohol beverage",
  "🍷": "wine drink alcohol beverage glass red",

  // Travel
  "🚗": "car vehicle automobile",
  "🚕": "taxi cab vehicle",
  "🚙": "suv vehicle car",
  "🚌": "bus vehicle",
  "🚎": "trolleybus vehicle",
  "🏎️": "race car vehicle fast",
  "🚓": "police car vehicle cop",
  "🚑": "ambulance vehicle emergency",
  "🚒": "fire truck vehicle emergency",
  "🚐": "minibus vehicle van",
  "🚚": "truck vehicle delivery",
  "🚛": "semi truck vehicle",
  "🚜": "tractor vehicle farm",
  "🏍️": "motorcycle vehicle bike",
  "🛵": "scooter vehicle",
  "🚲": "bicycle bike vehicle",
  "🛴": "scooter kick vehicle",
  "🚁": "helicopter vehicle aircraft",
  "✈️": "airplane aircraft vehicle plane",
  "🛩️": "small airplane aircraft vehicle",
  "🛫": "airplane departing takeoff travel",
  "🛬": "airplane arriving landing travel",
  "⛵": "sailboat boat ship water",
  "🚤": "speedboat boat ship water fast",
  "🛥️": "motor boat ship water",
  "🚢": "ship boat water cruise",
  "⚓": "anchor ship boat water",
  "🚧": "construction warning barrier hazard",
  "🚦": "traffic light signal",
  "🚥": "pedestrian crossing walk traffic",
  "🛤️": "railway track train travel",
  "🛣️": "motorway road travel",
  "⛽": "fuel pump gas station travel",
  "🚏": "stop sign traffic travel",

  // Sports & Activities
  "⚽": "soccer ball football sport game",
  "🏀": "basketball sport ball game",
  "🏈": "football sport ball american game",
  "⚾": "baseball sport ball game",
  "🎾": "tennis sport ball game",
  "🏐": "volleyball sport ball game",
  "🏉": "rugby sport ball game",
  "🎱": "pool billiards eight ball game",
  "🏓": "ping pong table tennis sport game",
  "🏸": "badminton sport game",
  "🏒": "hockey sport ice game",
  "🏑": "field hockey sport game",
  "🏏": "cricket sport game",
  "🏹": "archery bow arrow sport",
  "🎣": "fishing sport hobby rod",
  "🥊": "boxing glove sport fight",
  "🥋": "martial arts karate judo sport",
  "🛹": "skateboard sport",
  "⛸️": "ice skate sport winter",
  "🎿": "ski sport winter snow",
  "🏂": "snowboard sport winter",
  "🏋️": "weightlifting gym sport exercise fitness",
  "🤸": "gymnastics sport exercise cartwheel",
  "🧘": "yoga meditation exercise zen fitness",
  "🏄": "surfing sport water wave",
  "🏊": "swimming sport water pool",
  "🚴": "cycling biking sport exercise",
  "🏃": "running jogging sport exercise",
  "🤾": "handball sport game",
  "🤺": "fencing sport sword",
  "⛳": "golf sport flag hole",
  "🎯": "target bullseye direct hit goal aim darts",
  "🎲": "dice game gambling random chance",
  "🎮": "video game controller gaming play console",
  "🕹️": "joystick game controller arcade",
  "🎰": "slot machine gambling casino luck",
  "🧩": "puzzle piece jigsaw game",
  "♟️": "chess pawn game strategy board",
  "🎴": "cards game playing flower",
  "🃏": "joker card game playing wild",
  "🀄": "mahjong game tile",
  "🏆": "trophy winner champion award prize victory cup",
  "🥇": "first place medal gold winner",
  "🥈": "second place medal silver",
  "🥉": "third place medal bronze",
  "🏅": "sports medal award winner",
  "🎖️": "military medal award honor",

  // Locations & Flags
  "🌍": "globe earth africa europe world planet",
  "🌎": "globe earth americas world planet",
  "🌏": "globe earth asia australia world planet",
  "🗺️": "world map travel geography atlas",
  "🧭": "compass navigation direction travel",
  "🏔️": "mountain snow peak summit",
  "⛰️": "mountain hill nature",
  "🌋": "volcano eruption lava nature",
  "🏕️": "camping tent outdoors nature",
  "🏖️": "beach umbrella sun vacation holiday",
  "🏜️": "desert cactus sand dry",
  "🏝️": "desert island palm tropical vacation",
  "🏞️": "national park nature scenic landscape",
  "🏟️": "stadium arena sports venue",
  "🏗️": "construction building crane site",
  "🏘️": "houses neighborhood homes buildings",
  "🏙️": "cityscape city buildings urban skyline",
  "🏚️": "derelict house abandoned old",
  "🏛️": "classical building government museum pillars",
  "🏠": "house home building residence",
  "🏡": "house garden home building",
  "🏢": "office building work corporate business",
  "🏣": "japanese post office building",
  "🏤": "post office building mail",
  "🏥": "hospital medical health building emergency",
  "🏦": "bank building financial money institution",
  "🏨": "hotel building travel lodging",
  "🏩": "love hotel building",
  "🏪": "convenience store shop building",
  "🏫": "school building education",
  "🏬": "department store shop mall building",
  "🏭": "factory building industrial manufacturing",
  "🏯": "japanese castle building",
  "🏰": "castle building fortress medieval",
  "💒": "wedding chapel church building",
  "🗼": "tokyo tower japan building",
  "🗽": "statue liberty new york usa",
  "⛪": "church building religion christian",
  "🕌": "mosque building religion islam",
  "🛕": "hindu temple building religion",
  "🕍": "synagogue building religion jewish",
  "⛩️": "shinto shrine japan torii",
  "🕋": "kaaba mecca islam",
  "🏳️": "white flag surrender peace",
  "🏴": "black flag pirate",
  "🚩": "triangular flag red marker",
  "🎌": "crossed flags japan celebration",
  "🏁": "checkered flag racing finish winner",
  "🇺🇸": "usa united states america flag country",
  "🇬🇧": "uk united kingdom britain flag country",
  "🇨🇦": "canada flag country maple",
  "🇦🇺": "australia flag country",
  "🇯🇵": "japan flag country",
  "🇨🇳": "china flag country",
  "🇩🇪": "germany flag country",
  "🇫🇷": "france flag country",
  "🇮🇹": "italy flag country",
  "🇪🇸": "spain flag country",
  "🇧🇷": "brazil flag country",
  "🇲🇽": "mexico flag country",
  "🇮🇳": "india flag country",
  "🇰🇷": "korea south flag country",
  "🇷🇺": "russia flag country",
  "🇳🇱": "netherlands flag country dutch",
  "🇸🇪": "sweden flag country",
  "🇳🇴": "norway flag country",
  "🇩🇰": "denmark flag country",
  "🇫🇮": "finland flag country",
  "🇨🇭": "switzerland flag country",
  "🇦🇹": "austria flag country",
  "🇧🇪": "belgium flag country",
  "🇵🇱": "poland flag country",
  "🇵🇹": "portugal flag country",
  "🇬🇷": "greece flag country",
  "🇮🇪": "ireland flag country",
  "🇿🇦": "south africa flag country",
  "🇪🇬": "egypt flag country",
  "🇳🇿": "new zealand flag country",
  "🇸🇬": "singapore flag country",
  "🇹🇭": "thailand flag country",
  "🇻🇳": "vietnam flag country",
  "🇵🇭": "philippines flag country",
  "🇮🇩": "indonesia flag country",
  "🇲🇾": "malaysia flag country",
  "🇦🇪": "uae united arab emirates flag country dubai",
  "🇸🇦": "saudi arabia flag country",
  "🇮🇱": "israel flag country",
  "🇹🇷": "turkey flag country",
  "🇦🇷": "argentina flag country",
  "🇨🇱": "chile flag country",
  "🇨🇴": "colombia flag country",
  "🇵🇪": "peru flag country",
  "🇺🇦": "ukraine flag country",
}

const EMOJI_CATEGORIES = {
  Smileys: [
    "😀",
    "😃",
    "😄",
    "😁",
    "😆",
    "😅",
    "😂",
    "🤣",
    "😊",
    "😇",
    "🙂",
    "🙃",
    "😉",
    "😌",
    "😍",
    "🥰",
    "😘",
    "😗",
    "😙",
    "😚",
    "😋",
    "😛",
    "😝",
    "😜",
    "🤪",
    "🤨",
    "🧐",
    "🤓",
    "😎",
    "🤩",
    "🥳",
    "😏",
    "😒",
    "😞",
    "😔",
    "😟",
    "😕",
    "🙁",
    "☹️",
    "😣",
    "😖",
    "😫",
    "😩",
    "🥺",
    "😢",
    "😭",
    "😤",
    "😠",
    "😡",
    "🤬",
    "🤯",
    "😳",
    "🥵",
    "🥶",
    "😱",
    "😨",
    "😰",
    "😥",
    "😓",
    "🤗",
    "🤔",
    "🤭",
    "🤫",
    "🤥",
    "🤠",
    "👹",
    "👺",
    "👽",
    "👾",
    "🤖",
    "👻",
    "😈",
    "👿",
    "💀",
    "☠️",
    "🎃",
    "😺",
    "😸",
    "😹",
    "😻",
    "😼",
    "😽",
    "🙀",
    "😿",
    "😾",
    "👀",
    "👁️",
    "👓",
    "🕶️",
    "🥽",
  ],
  Hearts: [
    "❤️",
    "🧡",
    "💛",
    "💚",
    "💙",
    "💜",
    "🖤",
    "🤍",
    "🤎",
    "💔",
    "❣️",
    "💕",
    "💞",
    "💓",
    "💗",
    "💖",
    "💘",
    "💝",
    "💟",
    "❤️‍🔥",
    "❤️‍🩹",
    "✅",
    "☑️",
    "✔️",
    "❌",
    "❎",
    "✖️",
    "❓",
    "❔",
    "❗",
    "❕",
    "‼️",
    "⁉️",
    "⭕",
    "🔴",
    "🟠",
    "🟡",
    "🟢",
    "🔵",
    "🟣",
    "🟤",
    "⚫",
    "⚪",
    "🔺",
    "🔻",
    "🔶",
    "🔷",
    "🔸",
    "🔹",
    "🟥",
    "🟧",
    "🟨",
    "🟩",
    "🟦",
    "🟪",
    "🟫",
    "⬛",
    "⬜",
    "⭐",
    "🌟",
    "✨",
    "💫",
    "🌈",
    "☀️",
    "🌙",
    "⚡",
    "🔥",
    "💧",
    "🌊",
  ],
  People: [
    "👶",
    "🧒",
    "👦",
    "👧",
    "🧑",
    "👱",
    "👨",
    "🧔",
    "👩",
    "🧓",
    "👴",
    "👵",
    "💃",
    "🕺",
    "👨‍⚕️",
    "👩‍⚕️",
    "🧑‍⚕️",
    "👨‍🎓",
    "👩‍🎓",
    "🧑‍🎓",
    "👨‍🏫",
    "👩‍🏫",
    "🧑‍🏫",
    "👨‍⚖️",
    "👩‍⚖️",
    "🧑‍⚖️",
    "👨‍🌾",
    "👩‍🌾",
    "🧑‍🌾",
    "👨‍🍳",
    "👩‍🍳",
    "🧑‍🍳",
    "👨‍🔧",
    "👩‍🔧",
    "🧑‍🔧",
    "👨‍🏭",
    "👩‍🏭",
    "🧑‍🏭",
    "👨‍💼",
    "👩‍💼",
    "🧑‍💼",
    "👨‍🔬",
    "👩‍🔬",
    "🧑‍🔬",
    "👨‍💻",
    "👩‍💻",
    "🧑‍💻",
    "👨‍🎤",
    "👩‍🎤",
    "🧑‍🎤",
    "👨‍🎨",
    "👩‍🎨",
    "🧑‍🎨",
    "👨‍✈️",
    "👩‍✈️",
    "🧑‍✈️",
    "👨‍🚀",
    "👩‍🚀",
    "🧑‍🚀",
    "👨‍🚒",
    "👩‍🚒",
    "🧑‍🚒",
    "👮",
    "🕵️",
    "💂",
    "👷",
    "🤴",
    "👸",
    "👳",
    "👲",
    "🧕",
    "🤵",
    "👰",
    "🤰",
    "🤱",
    "👼",
    "🎅",
    "🤶",
    "🦸",
    "🦹",
    "🧙",
    "🧚",
    "🧛",
    "🧜",
    "🧝",
    "🧞",
    "🧟",
    "💆",
  ],
  Animals: [
    "🐶",
    "🐱",
    "🐭",
    "🐹",
    "🐰",
    "🦊",
    "🐻",
    "🐼",
    "🐨",
    "🐯",
    "🦁",
    "🐮",
    "🐷",
    "🐽",
    "🐸",
    "🐵",
    "🙈",
    "🙉",
    "🙊",
    "🐒",
    "🐔",
    "🐧",
    "🐦",
    "🐤",
    "🐣",
    "🐥",
    "🦆",
    "🦅",
    "🦉",
    "🦇",
    "🐺",
    "🐗",
    "🐴",
    "🦄",
    "🐝",
    "🐛",
    "🦋",
    "🐌",
    "🐞",
    "🐜",
    "🦟",
    "🦗",
    "🕷️",
    "🦂",
    "🐢",
    "🐍",
    "🦎",
    "🦖",
  ],
  Food: [
    "🍎",
    "🍐",
    "🍊",
    "🍋",
    "🍌",
    "🍉",
    "🍇",
    "🍓",
    "🍈",
    "🍒",
    "🍑",
    "🥭",
    "🍍",
    "🥥",
    "🥝",
    "🍅",
    "🍆",
    "🥑",
    "🥦",
    "🥒",
    "🌶️",
    "🌽",
    "🥕",
    "🥔",
    "🍠",
    "🥐",
    "🥖",
    "🍞",
    "🧀",
    "🥚",
    "🍳",
    "🥞",
    "🥓",
    "🥩",
    "🍗",
    "🍖",
    "🌭",
    "☕",
    "🍵",
    "🍺",
    "🍷",
  ],
  Travel: [
    "🚗",
    "🚕",
    "🚙",
    "🚌",
    "🚎",
    "🏎️",
    "🚓",
    "🚑",
    "🚒",
    "🚐",
    "🚚",
    "🚛",
    "🚜",
    "🏍️",
    "🛵",
    "🚲",
    "🛴",
    "🚁",
    "✈️",
    "🛩️",
    "🛫",
    "🛬",
    "⛵",
    "🚤",
    "🛥️",
    "🚢",
    "⚓",
    "🚧",
    "🚦",
    "🚥",
    "🛤️",
    "🛣️",
    "⛽",
    "🚏",
  ],
  Sports: [
    "⚽",
    "🏀",
    "🏈",
    "⚾",
    "🎾",
    "🏐",
    "🏉",
    "🎱",
    "🏓",
    "🏸",
    "🏒",
    "🏑",
    "🏏",
    "🏹",
    "🎣",
    "🥊",
    "🥋",
    "🛹",
    "⛸️",
    "🎿",
    "🏂",
    "🏋️",
    "🤸",
    "🧘",
    "🏄",
    "🏊",
    "🚴",
    "🏃",
    "🤾",
    "🤺",
    "⛳",
    "🎯",
    "🎲",
    "🎮",
    "🕹️",
    "🎰",
    "🧩",
    "♟️",
    "🎴",
    "🃏",
    "🀄",
    "🏆",
    "🥇",
    "🥈",
    "🥉",
    "🏅",
    "🎖️",
  ],
  Locations: [
    "🌍",
    "🌎",
    "🌏",
    "🗺️",
    "🧭",
    "🏔️",
    "⛰️",
    "🌋",
    "🏕️",
    "🏖️",
    "🏜️",
    "🏝️",
    "🏞️",
    "🏟️",
    "🏗️",
    "🏘️",
    "🏙️",
    "🏚️",
    "🏛️",
    "🏠",
    "🏡",
    "🏢",
    "🏣",
    "🏤",
    "🏥",
    "🏦",
    "🏨",
    "🏩",
    "🏪",
    "🏫",
    "🏬",
    "🏭",
    "🏯",
    "🏰",
    "💒",
    "🗼",
    "🗽",
    "⛪",
    "🕌",
    "🛕",
    "🕍",
    "⛩️",
    "🕋",
    "🏳️",
    "🏴",
    "🚩",
    "🎌",
    "🏁",
    "🇺🇸",
    "🇬🇧",
    "🇨🇦",
    "🇦🇺",
    "🇯🇵",
    "🇨🇳",
    "🇩🇪",
    "🇫🇷",
    "🇮🇹",
    "🇪🇸",
    "🇧🇷",
    "🇲🇽",
    "🇮🇳",
    "🇰🇷",
    "🇷🇺",
    "🇳🇱",
    "🇸🇪",
    "🇳🇴",
    "🇩🇰",
    "🇫🇮",
    "🇨🇭",
    "🇦🇹",
    "🇧🇪",
    "🇵🇱",
    "🇵🇹",
    "🇬🇷",
    "🇮🇪",
    "🇿🇦",
    "🇪🇬",
    "🇳🇿",
    "🇸🇬",
    "🇹🇭",
    "🇻🇳",
    "🇵🇭",
    "🇮🇩",
    "🇲🇾",
    "🇦🇪",
    "🇸🇦",
    "🇮🇱",
    "🇹🇷",
    "🇦🇷",
    "🇨🇱",
    "🇨🇴",
    "🇵🇪",
    "🇺🇦",
  ],
  Data: [
    "📊",
    "📈",
    "📉",
    "💹",
    "📋",
    "📁",
    "📂",
    "🗂️",
    "🗃️",
    "🗄️",
    "📄",
    "📃",
    "📑",
    "📝",
    "📒",
    "📓",
    "📔",
    "📕",
    "📗",
    "📘",
    "📙",
    "📚",
    "🔢",
    "🔣",
    "🔤",
    "🔡",
    "🔠",
    "💾",
    "💿",
    "📀",
    "🧮",
    "📐",
    "📏",
    "🔬",
    "🔭",
    "📡",
    "🗑️",
    "📥",
    "📤",
    "📦",
  ],
  Multimedia: [
    "🎵",
    "🎶",
    "🎼",
    "🎤",
    "🎧",
    "🎷",
    "🎸",
    "🎹",
    "🎺",
    "🎻",
    "🥁",
    "📻",
    "📺",
    "🎬",
    "🎥",
    "📹",
    "📷",
    "📸",
    "🖼️",
    "🎨",
    "🖌️",
    "🖍️",
    "🎭",
    "🎪",
    "🎰",
    "🎮",
    "🕹️",
    "🎲",
    "🧩",
    "📽️",
    "📼",
    "📱",
    "💻",
    "🖥️",
    "🖨️",
    "⌨️",
    "🖱️",
    "🔊",
    "🔉",
    "🔈",
  ],
  Technical: [
    "🔒",
    "🔓",
    "🔐",
    "🔑",
    "🗝️",
    "🛡️",
    "⚔️",
    "🔱",
    "⚙️",
    "🔧",
    "🔨",
    "⛏️",
    "🛠️",
    "🔩",
    "⚡",
    "🔌",
    "💡",
    "🔦",
    "🕯️",
    "🧯",
    "🚨",
    "🚔",
    "🔍",
    "🔎",
    "🧲",
    "🧪",
    "🧫",
    "🧬",
    "💉",
    "💊",
    "🩺",
    "🩹",
    "🩻",
    "🔗",
    "⛓️",
    "🧰",
    "🪛",
    "🪜",
    "🪝",
    "🪤",
  ],
  Office: [
    "📅",
    "📆",
    "🗓️",
    "📇",
    "🗒️",
    "🗃️",
    "📰",
    "🗞️",
    "📌",
    "📍",
    "📎",
    "🖇️",
    "📐",
    "📏",
    "✂️",
    "🖊️",
    "🖋️",
    "✒️",
    "📝",
    "✏️",
    "🔖",
    "🏷️",
    "💼",
    "📁",
    "📂",
    "🗂️",
    "📋",
    "📊",
    "📈",
    "📉",
    "🗳️",
    "✉️",
    "📧",
    "📨",
    "📩",
    "📪",
    "📫",
    "📬",
    "📭",
    "📮",
  ],
}

export function EmojiPicker({ value, onChange, inline = false }: EmojiPickerProps) {
  const [searchTerm, setSearchTerm] = useState("")
  const [activeTab, setActiveTab] = useState("Smileys")
  const [open, setOpen] = useState(false)

  const allEmojis = useMemo(() => Object.values(EMOJI_CATEGORIES).flat(), [])

  const filteredEmojis = useMemo(() => {
    if (!searchTerm) return EMOJI_CATEGORIES[activeTab as keyof typeof EMOJI_CATEGORIES] || []

    const searchLower = searchTerm.toLowerCase()
    return allEmojis.filter((emoji) => {
      const emojiName = EMOJI_NAMES[emoji] || ""
      return emoji.toLowerCase().includes(searchLower) || emojiName.toLowerCase().includes(searchLower)
    })
  }, [searchTerm, activeTab, allEmojis])

  const handleEmojiSelect = (emoji: string) => {
    onChange(emoji)
    setOpen(false)
  }

  if (inline) {
    return (
      <div className="space-y-2 w-full">
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" className="w-10 h-10 p-0 text-xl cursor-pointer hover:bg-muted border">
            {value || "😀"}
          </Button>
          <div className="grid grid-cols-6 gap-1 flex-1">
            {EMOJI_CATEGORIES.Smileys.slice(0, 6).map((emoji) => (
              <Button
                key={emoji}
                variant="ghost"
                size="sm"
                className="w-8 h-8 p-0 text-lg hover:bg-muted cursor-pointer"
                onClick={() => handleEmojiSelect(emoji)}
              >
                {emoji}
              </Button>
            ))}
          </div>
        </div>
        <div className="grid grid-cols-8 gap-1">
          {EMOJI_CATEGORIES.Objects.slice(0, 16).map((emoji) => (
            <Button
              key={emoji}
              variant="ghost"
              size="sm"
              className="w-8 h-8 p-0 text-lg hover:bg-muted cursor-pointer"
              onClick={() => handleEmojiSelect(emoji)}
            >
              {emoji}
            </Button>
          ))}
        </div>
      </div>
    )
  }

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger className="w-8 h-8 p-0 text-lg cursor-pointer hover:bg-muted inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 hover:bg-accent hover:text-accent-foreground">
        {value || "😀"}
      </PopoverTrigger>
      <PopoverContent
        className="w-96 p-3 z-50"
        side="bottom"
        align="start"
        sideOffset={8}
        collisionPadding={10}
        avoidCollisions={true}
        sticky="always"
        onCloseAutoFocus={(e) => e.preventDefault()}
      >
        <div className="space-y-3">
          <div className="relative">
            <Search className="w-4 h-4 absolute left-2 top-1/2 transform -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder="Search emojis..."
              className="pl-8 h-8"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>

          {!searchTerm ? (
            <Tabs value={activeTab} onValueChange={setActiveTab}>
              <TabsList className="grid w-full grid-cols-4">
                <TabsTrigger value="Smileys" className="text-xs cursor-pointer">
                  😀
                </TabsTrigger>
                <TabsTrigger value="Hearts" className="text-xs cursor-pointer">
                  ❤️
                </TabsTrigger>
                <TabsTrigger value="People" className="text-xs cursor-pointer">
                  👤
                </TabsTrigger>
                <TabsTrigger value="Animals" className="text-xs cursor-pointer">
                  🐶
                </TabsTrigger>
              </TabsList>
              <TabsList className="grid w-full grid-cols-4 mt-1">
                <TabsTrigger value="Food" className="text-xs cursor-pointer">
                  🍎
                </TabsTrigger>
                <TabsTrigger value="Travel" className="text-xs cursor-pointer">
                  🚗
                </TabsTrigger>
                <TabsTrigger value="Sports" className="text-xs cursor-pointer">
                  ⚽
                </TabsTrigger>
                <TabsTrigger value="Locations" className="text-xs cursor-pointer">
                  🌍
                </TabsTrigger>
              </TabsList>
              <TabsList className="grid w-full grid-cols-4 mt-1">
                <TabsTrigger value="Data" className="text-xs cursor-pointer">
                  📊
                </TabsTrigger>
                <TabsTrigger value="Multimedia" className="text-xs cursor-pointer">
                  🎵
                </TabsTrigger>
                <TabsTrigger value="Technical" className="text-xs cursor-pointer">
                  🔒
                </TabsTrigger>
                <TabsTrigger value="Office" className="text-xs cursor-pointer">
                  📅
                </TabsTrigger>
              </TabsList>

              {Object.entries(EMOJI_CATEGORIES).map(([category, emojis]) => (
                <TabsContent key={category} value={category} className="mt-2">
                  <div className="grid grid-cols-8 gap-1 max-h-48 overflow-y-auto">
                    {emojis.map((emoji) => (
                      <Button
                        key={emoji}
                        variant="ghost"
                        size="sm"
                        className="w-8 h-8 p-0 text-lg hover:bg-muted cursor-pointer"
                        onClick={() => handleEmojiSelect(emoji)}
                      >
                        {emoji}
                      </Button>
                    ))}
                  </div>
                </TabsContent>
              ))}
            </Tabs>
          ) : (
            <div className="grid grid-cols-8 gap-1 max-h-48 overflow-y-auto">
              {filteredEmojis.length > 0 ? (
                filteredEmojis.map((emoji) => (
                  <Button
                    key={emoji}
                    variant="ghost"
                    size="sm"
                    className="w-8 h-8 p-0 text-lg hover:bg-muted cursor-pointer"
                    onClick={() => handleEmojiSelect(emoji)}
                  >
                    {emoji}
                  </Button>
                ))
              ) : (
                <div className="col-span-8 text-center text-sm text-muted-foreground py-4">No emojis found</div>
              )}
            </div>
          )}
        </div>
      </PopoverContent>
    </Popover>
  )
}
