"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Search } from "lucide-react"

interface EmojiPickerProps {
  value: string
  onChange: (emoji: string) => void
  inline?: boolean
}

const EMOJI_NAMES: Record<string, string> = {
  "😀": "grinning face smile happy",
  "😃": "grinning face smile happy joy",
  "😄": "grinning face smile happy joy laugh",
  "😁": "beaming face smile happy grin",
  "😆": "laughing face smile happy lol",
  "😅": "sweat smile nervous laugh",
  "😂": "joy tears laugh crying funny lol",
  "🤣": "rolling laugh floor funny lol rofl",
  "😊": "smile blush happy pleased",
  "😇": "angel halo innocent smile",
  "🙂": "smile slight happy",
  "🙃": "upside down smile sarcastic",
  "😉": "wink flirt smile",
  "😌": "relieved smile peaceful calm",
  "😍": "heart eyes love adore",
  "🥰": "smiling hearts love adore",
  "😘": "kiss love heart",
  "😗": "kiss smile",
  "😙": "kiss smile",
  "😚": "kiss smile closed eyes",
  "😋": "yum delicious food tasty hungry",
  "😛": "tongue out playful",
  "😝": "tongue wink playful",
  "😜": "tongue wink playful",
  "🤪": "zany crazy wild silly",
  "🤨": "raised eyebrow skeptical suspicious",
  "🧐": "monocle thinking curious",
  "🤓": "nerd glasses geek smart",
  "😎": "cool sunglasses awesome",
  "🤩": "star struck amazed wow",
  "🥳": "party celebrate birthday",
  "😏": "smirk sly confident",
  "😒": "unamused annoyed bored",
  "😞": "disappointed sad unhappy",
  "😔": "pensive sad thoughtful",
  "😟": "worried anxious concerned",
  "😕": "confused puzzled uncertain",
  "🙁": "frown sad unhappy",
  "☹️": "frown sad unhappy",
  "😣": "persevere struggle difficult",
  "😖": "confounded frustrated upset",
  "😫": "tired exhausted weary",
  "😩": "weary tired exhausted",
  "🥺": "pleading puppy eyes sad",
  "😢": "cry sad tears",
  "😭": "crying tears sob sad",
  "😤": "triumph proud steam",
  "😠": "angry mad upset",
  "😡": "rage angry furious mad",
  "🤬": "cursing swearing angry symbols",
  "🤯": "mind blown exploding shocked",
  "😳": "flushed embarrassed surprised",
  "🥵": "hot sweat heat",
  "🥶": "cold freezing ice",
  "😱": "scream fear scared shocked",
  "😨": "fearful scared afraid",
  "😰": "anxious nervous worried sweat",
  "😥": "sad sweat disappointed",
  "😓": "downcast sweat tired",
  "🤗": "hugging hug embrace",
  "🤔": "thinking hmm consider",
  "🤭": "hand over mouth oops giggle",
  "🤫": "shush quiet silence",
  "🤥": "lying pinocchio nose",
  "👀": "eyes looking watching see vision",
  "👁️": "eye looking watching see vision",
  "👓": "glasses eyeglasses spectacles vision reading",
  "🕶️": "sunglasses cool shades dark glasses",
  "🥽": "goggles safety swimming diving protection",
  "👶": "baby infant child",
  "🧒": "child kid young",
  "👦": "boy child kid",
  "👧": "girl child kid",
  "🧑": "person adult human",
  "👱": "person blonde hair",
  "👨": "man male adult",
  "🧔": "man beard facial hair",
  "👩": "woman female adult",
  "🧓": "older person elderly senior",
  "👴": "old man elderly grandfather",
  "👵": "old woman elderly grandmother",
  "💃": "woman dancing dance party celebration",
  "🕺": "man dancing dance party celebration",
  "🤖": "robot machine ai artificial intelligence",
  "👨‍⚕️": "man doctor health medical physician",
  "👩‍⚕️": "woman doctor health medical physician",
  "🧑‍⚕️": "person doctor health medical physician",
  "👨‍🎓": "man student graduate education",
  "👩‍🎓": "woman student graduate education",
  "🧑‍🎓": "person student graduate education",
  "👨‍🏫": "man teacher professor education instructor",
  "👩‍🏫": "woman teacher professor education instructor",
  "🧑‍🏫": "person teacher professor education instructor",
  "👨‍⚖️": "man judge law court justice",
  "👩‍⚖️": "woman judge law court justice",
  "🧑‍⚖️": "person judge law court justice",
  "👨‍🌾": "man farmer agriculture farming",
  "👩‍🌾": "woman farmer agriculture farming",
  "🧑‍🌾": "person farmer agriculture farming",
  "👨‍🍳": "man cook chef cooking kitchen",
  "👩‍🍳": "woman cook chef cooking kitchen",
  "🧑‍🍳": "person cook chef cooking kitchen",
  "👨‍🔧": "man mechanic repair technician",
  "👩‍🔧": "woman mechanic repair technician",
  "🧑‍🔧": "person mechanic repair technician",
  "👨‍🏭": "man factory worker industrial",
  "👩‍🏭": "woman factory worker industrial",
  "🧑‍🏭": "person factory worker industrial",
  "👨‍💼": "man office worker business professional",
  "👩‍💼": "woman office worker business professional",
  "🧑‍💼": "person office worker business professional",
  "👨‍🔬": "man scientist research lab",
  "👩‍🔬": "woman scientist research lab",
  "🧑‍🔬": "person scientist research lab",
  "👨‍💻": "man technologist programmer developer coder",
  "👩‍💻": "woman technologist programmer developer coder",
  "🧑‍💻": "person technologist programmer developer coder",
  "👨‍🎤": "man singer musician performer artist",
  "👩‍🎤": "woman singer musician performer artist",
  "🧑‍🎤": "person singer musician performer artist",
  "👨‍🎨": "man artist painter creative",
  "👩‍🎨": "woman artist painter creative",
  "🧑‍🎨": "person artist painter creative",
  "👨‍✈️": "man pilot aviation airplane",
  "👩‍✈️": "woman pilot aviation airplane",
  "🧑‍✈️": "person pilot aviation airplane",
  "👨‍🚀": "man astronaut space rocket",
  "👩‍🚀": "woman astronaut space rocket",
  "🧑‍🚀": "person astronaut space rocket",
  "👨‍🚒": "man firefighter fire emergency",
  "👩‍🚒": "woman firefighter fire emergency",
  "🧑‍🚒": "person firefighter fire emergency",
  "👮": "police officer cop law enforcement",
  "🕵️": "detective spy investigator",
  "💂": "guard soldier",
  "👷": "construction worker builder",
  "🤴": "prince royal",
  "👸": "princess royal",
  "👳": "person turban",
  "👲": "person skullcap",
  "🧕": "person headscarf",
  "🤵": "person tuxedo",
  "👰": "person veil bride",
  "🤰": "pregnant woman",
  "🤱": "breast feeding",
  "👼": "baby angel",
  "🎅": "santa claus christmas",
  "🤶": "mrs claus christmas",
  "🦸": "superhero hero",
  "🦹": "supervillain villain",
  "🧙": "mage wizard",
  "🧚": "fairy magic",
  "🧛": "vampire",
  "🧜": "merperson mermaid",
  "🧝": "elf",
  "🧞": "genie",
  "🧟": "zombie",
  "💆": "person massage spa",
  "🐶": "dog puppy pet animal",
  "🐱": "cat kitten pet animal",
  "🐭": "mouse rat animal",
  "🐹": "hamster pet animal",
  "🐰": "rabbit bunny animal",
  "🦊": "fox animal",
  "🐻": "bear animal",
  "🐼": "panda bear animal",
  "🐨": "koala bear animal",
  "🐯": "tiger animal",
  "🦁": "lion animal king",
  "🐮": "cow animal farm",
  "🐷": "pig animal farm",
  "🐽": "pig nose snout",
  "🐸": "frog animal",
  "🐵": "monkey animal",
  "🙈": "see no evil monkey",
  "🙉": "hear no evil monkey",
  "🙊": "speak no evil monkey",
  "🐒": "monkey animal",
  "🐔": "chicken rooster bird farm",
  "🐧": "penguin bird animal",
  "🐦": "bird animal",
  "🐤": "baby chick bird",
  "🐣": "hatching chick bird egg",
  "🐥": "baby chick bird",
  "🦆": "duck bird animal",
  "🦅": "eagle bird animal",
  "🦉": "owl bird animal night",
  "🦇": "bat animal night",
  "🐺": "wolf animal",
  "🐗": "boar pig animal",
  "🐴": "horse animal",
  "🦄": "unicorn horse magical",
  "🐝": "bee insect honey",
  "🐛": "bug caterpillar insect",
  "🦋": "butterfly insect",
  "🐌": "snail slow animal",
  "🐞": "ladybug insect",
  "🐜": "ant insect",
  "🦟": "mosquito insect",
  "🦗": "cricket insect",
  "🕷️": "spider insect",
  "🦂": "scorpion insect",
  "🐢": "turtle animal",
  "🐍": "snake animal",
  "🦎": "lizard animal",
  "🦖": "dinosaur animal",
  "🍎": "apple fruit red food",
  "🍐": "pear fruit food",
  "🍊": "orange fruit food citrus",
  "🍋": "lemon fruit food citrus sour",
  "🍌": "banana fruit food yellow",
  "🍉": "watermelon fruit food summer",
  "🍇": "grapes fruit food purple",
  "🍓": "strawberry fruit food red berry",
  "🍈": "melon fruit food",
  "🍒": "cherries fruit food red",
  "🍑": "peach fruit food",
  "🥭": "mango fruit food tropical",
  "🍍": "pineapple fruit food tropical",
  "🥥": "coconut fruit food tropical",
  "🥝": "kiwi fruit food green",
  "🍅": "tomato vegetable food red",
  "🍆": "eggplant vegetable food purple",
  "🥑": "avocado fruit food green",
  "🥦": "broccoli vegetable food green",
  "🥒": "cucumber vegetable food green",
  "🌶️": "pepper hot spicy food",
  "🌽": "corn vegetable food yellow",
  "🥕": "carrot vegetable food orange",
  "🥔": "potato vegetable food",
  "🍠": "sweet potato vegetable food",
  "🥐": "croissant bread food pastry",
  "🥖": "baguette bread food french",
  "🍞": "bread food loaf",
  "🧀": "cheese food dairy",
  "🥚": "egg food breakfast",
  "🍳": "cooking egg food breakfast",
  "🥞": "pancakes food breakfast",
  "🥓": "bacon food breakfast meat",
  "🥩": "meat steak food",
  "🍗": "chicken leg food meat",
  "🍖": "meat bone food",
  "🌭": "hot dog food",
  "⚽": "soccer ball football sport",
  "🏀": "basketball sport ball",
  "🏈": "football sport ball american",
  "⚾": "baseball sport ball",
  "🎾": "tennis sport ball",
  "🏐": "volleyball sport ball",
  "🏉": "rugby sport ball",
  "🎱": "pool billiards eight ball",
  "🏓": "ping pong table tennis sport",
  "🏸": "badminton sport",
  "🏒": "hockey sport ice",
  "🏑": "field hockey sport",
  "🏏": "cricket sport",
  "🏹": "archery bow arrow sport",
  "🎣": "fishing sport hobby",
  "🥊": "boxing glove sport fight",
  "🥋": "martial arts karate judo sport",
  "🛹": "skateboard sport",
  "⛸️": "ice skate sport winter",
  "🎿": "ski sport winter snow",
  "🏂": "snowboard sport winter",
  "🏋️": "weightlifting gym sport exercise",
  "🤸": "gymnastics sport exercise",
  "🧘": "yoga meditation exercise",
  "🏄": "surfing sport water",
  "🏊": "swimming sport water",
  "🚗": "car vehicle automobile",
  "🚕": "taxi cab vehicle",
  "🚙": "suv vehicle car",
  "🚌": "bus vehicle",
  "🚎": "trolleybus vehicle",
  "🏎️": "race car vehicle fast",
  "🚓": "police car vehicle cop",
  "🚑": "ambulance vehicle emergency",
  "🚒": "fire truck vehicle emergency",
  "🚐": "minibus vehicle van",
  "🚚": "truck vehicle delivery",
  "🚛": "semi truck vehicle",
  "🚜": "tractor vehicle farm",
  "🏍️": "motorcycle vehicle bike",
  "🛵": "scooter vehicle",
  "🚲": "bicycle bike vehicle",
  "🛴": "scooter kick vehicle",
  "🚁": "helicopter vehicle aircraft",
  "✈️": "airplane aircraft vehicle plane",
  "🛩️": "small airplane aircraft vehicle",
  "⛵": "sailboat boat ship water",
  "🚤": "speedboat boat ship water fast",
  "🛥️": "motor boat ship water",
  "🚢": "ship boat water cruise",
  "⚓": "anchor ship boat water",
  "🚧": "construction warning barrier hazard",
  "🚦": "traffic light signal",
  "🗺️": "map world travel",
  "🗽": "statue liberty new york",
  "🗼": "tokyo tower japan",
  "🏰": "castle building fortress",
  "🏯": "japanese castle building",
  "🎡": "ferris wheel amusement park",
  "🎢": "roller coaster amusement park",
  "🎠": "carousel horse amusement park",
  "⌚": "watch time clock",
  "📱": "phone mobile smartphone",
  "💻": "laptop computer technology work office device",
  "⌨️": "keyboard typing computer input device",
  "🖥️": "desktop computer technology work office device pc",
  "🖨️": "printer print document office device",
  "🖱️": "computer mouse click device input",
  "💽": "computer disk minidisk storage data",
  "💾": "floppy disk save storage data old",
  "💿": "optical disk cd storage data",
  "📀": "dvd disk storage data media",
  "📅": "calendar date schedule appointment meeting day planner",
  "📆": "calendar date schedule appointment meeting day planner",
  "🗓️": "calendar date schedule appointment meeting day planner",
  "📇": "card rolodex contacts business cards",
  "🗂️": "card file dividers organize filing folders tabs",
  "🗃️": "card file box storage organize filing archive",
  "🗄️": "file cabinet office storage organize archive",
  "📋": "clipboard document list checklist tasks",
  "📊": "bar chart data graph statistics report analytics presentation",
  "📈": "chart increasing upward growth success profit metrics analytics",
  "📉": "chart decreasing downward decline loss metrics analytics",
  "💹": "chart upward trend stock market finance profit",
  "📁": "folder directory files organize documents storage",
  "📂": "folder open directory files organize documents storage",
  "📄": "document page paper file text",
  "📃": "document page paper file text scroll",
  "📑": "bookmark tabs document file reference report",
  "📰": "newspaper news article press media",
  "🗞️": "newspaper rolled news article press media",
  "📓": "notebook journal writing notes diary",
  "📔": "notebook journal writing notes diary decorative",
  "📒": "ledger account book record finance",
  "📕": "closed book text reading red",
  "📗": "open book text reading green",
  "📘": "open book text reading blue",
  "📙": "open book text reading orange",
  "📚": "books library reading education study",
  "📖": "open book reading text education study",
  "🔖": "bookmark save reference mark page",
  "🗒️": "spiral notepad notes writing memo",
  "📝": "memo note writing document text pencil",
  "✉️": "envelope mail email letter message post",
  "📧": "email mail message inbox electronic",
  "📨": "incoming envelope mail email message received",
  "📩": "envelope arrow mail email message send",
  "📤": "outbox tray mail send email message",
  "📥": "inbox tray mail receive email message",
  "📦": "package box shipping delivery parcel",
  "📫": "mailbox closed mail post letter",
  "📪": "mailbox closed mail post letter",
  "📬": "mailbox open mail post letter",
  "📭": "mailbox open mail post letter",
  "📮": "postbox mail post letter",
  "🗳️": "ballot box vote election",
  "✏️": "pencil write edit draw",
  "✒️": "pen write edit signature",
  "🖊️": "pen write edit signature",
  "🖋️": "fountain pen write edit signature formal",
  "📌": "pushpin pin notice board mark important",
  "📍": "round pushpin pin location mark map",
  "🖇️": "linked paperclips attach connect document",
  "📎": "paperclip attach link document file",
  "📐": "triangular ruler measure angle geometry math",
  "🔗": "link chain connection url hyperlink",
  "⛓️": "chains link connection locked",
  "🧷": "safety pin pin attach fasten",
  "🔧": "wrench tool fix repair settings",
  "🔨": "hammer tool build fix construct",
  "⚒️": "hammer pick tools build mining",
  "🛠️": "hammer wrench tools fix repair settings",
  "⚙️": "gear settings configuration mechanical cog",
  "🔩": "nut bolt hardware fastener",
  "⚡": "high voltage lightning electricity power energy fast",
  "🔋": "battery power energy charge",
  "🔌": "electric plug power energy outlet",
  "💡": "light bulb idea bright lamp illumination",
  "🔦": "flashlight torch light",
  "🕯️": "candle light flame fire",
  "🪔": "diya lamp light",
  "💵": "dollar banknote money cash currency",
  "💴": "yen banknote money cash currency",
  "💶": "euro banknote money cash currency",
  "💷": "pound banknote money cash currency",
  "💰": "money bag cash wealth rich savings",
  "💳": "credit card payment bank finance",
  "💸": "money wings cash spending flying",
  "🏦": "bank building financial money institution",
  "📐": "triangular ruler measure angle geometry",
  "🖌️": "paintbrush brush art creative design",
  "🖍️": "crayon draw color art",
  "🎭": "performing arts theater mask drama",
  "🖼️": "framed picture art painting photo image",
  "🎨": "artist palette art paint creative design",
}

const EMOJI_CATEGORIES = {
  Smileys: [
    "😀",
    "😃",
    "😄",
    "😁",
    "😆",
    "😅",
    "😂",
    "🤣",
    "😊",
    "😇",
    "🙂",
    "🙃",
    "😉",
    "😌",
    "😍",
    "🥰",
    "😘",
    "😗",
    "😙",
    "😚",
    "😋",
    "😛",
    "😝",
    "😜",
    "🤪",
    "🤨",
    "🧐",
    "🤓",
    "😎",
    "🤩",
    "🥳",
    "😏",
    "😒",
    "😞",
    "😔",
    "😟",
    "😕",
    "🙁",
    "☹️",
    "😣",
    "😖",
    "😫",
    "😩",
    "🥺",
    "😢",
    "😭",
    "😤",
    "😠",
    "😡",
    "🤬",
    "🤯",
    "😳",
    "🥵",
    "🥶",
    "😱",
    "😨",
    "😰",
    "😥",
    "😓",
    "🤗",
    "🤔",
    "🤭",
    "🤫",
    "🤥",
    "👀",
    "👁️",
    "👓",
    "🕶️",
    "🥽",
  ],
  People: [
    "👶",
    "🧒",
    "👦",
    "👧",
    "🧑",
    "👱",
    "👨",
    "🧔",
    "👩",
    "🧓",
    "👴",
    "👵",
    "💃",
    "🕺",
    "🤖",
    "👨‍⚕️",
    "👩‍⚕️",
    "🧑‍⚕️",
    "👨‍🎓",
    "👩‍🎓",
    "🧑‍🎓",
    "👨‍🏫",
    "👩‍🏫",
    "🧑‍🏫",
    "👨‍⚖️",
    "👩‍⚖️",
    "🧑‍⚖️",
    "👨‍🌾",
    "👩‍🌾",
    "🧑‍🌾",
    "👨‍🍳",
    "👩‍🍳",
    "🧑‍🍳",
    "👨‍🔧",
    "👩‍🔧",
    "🧑‍🔧",
    "👨‍🏭",
    "👩‍🏭",
    "🧑‍🏭",
    "👨‍💼",
    "👩‍💼",
    "🧑‍💼",
    "👨‍🔬",
    "👩‍🔬",
    "🧑‍🔬",
    "👨‍💻",
    "👩‍💻",
    "🧑‍💻",
    "👨‍🎤",
    "👩‍🎤",
    "🧑‍🎤",
    "👨‍🎨",
    "👩‍🎨",
    "🧑‍🎨",
    "👨‍✈️",
    "👩‍✈️",
    "🧑‍✈️",
    "👨‍🚀",
    "👩‍🚀",
    "🧑‍🚀",
    "👨‍🚒",
    "👩‍🚒",
    "🧑‍🚒",
    "👮",
    "🕵️",
    "💂",
    "👷",
    "🤴",
    "👸",
    "👳",
    "👲",
    "🧕",
    "🤵",
    "👰",
    "🤰",
    "🤱",
    "👼",
    "🎅",
    "🤶",
    "🦸",
    "🦹",
    "🧙",
    "🧚",
    "🧛",
    "🧜",
    "🧝",
    "🧞",
    "🧟",
    "💆",
  ],
  Animals: [
    "🐶",
    "🐱",
    "🐭",
    "🐹",
    "🐰",
    "🦊",
    "🐻",
    "🐼",
    "🐨",
    "🐯",
    "🦁",
    "🐮",
    "🐷",
    "🐽",
    "🐸",
    "🐵",
    "🙈",
    "🙉",
    "🙊",
    "🐒",
    "🐔",
    "🐧",
    "🐦",
    "🐤",
    "🐣",
    "🐥",
    "🦆",
    "🦅",
    "🦉",
    "🦇",
    "🐺",
    "🐗",
    "🐴",
    "🦄",
    "🐝",
    "🐛",
    "🦋",
    "🐌",
    "🐞",
    "🐜",
    "🦟",
    "🦗",
    "🕷️",
    "🦂",
    "🐢",
    "🐍",
    "🦎",
    "🦖",
  ],
  Food: [
    "🍎",
    "🍐",
    "🍊",
    "🍋",
    "🍌",
    "🍉",
    "🍇",
    "🍓",
    "🍈",
    "🍒",
    "🍑",
    "🥭",
    "🍍",
    "🥥",
    "🥝",
    "🍅",
    "🍆",
    "🥑",
    "🥦",
    "🥒",
    "🌶️",
    "🌽",
    "🥕",
    "🥔",
    "🍠",
    "🥐",
    "🥖",
    "🍞",
    "🧀",
    "🥚",
    "🍳",
    "🥞",
    "🥓",
    "🥩",
    "🍗",
    "🍖",
    "🌭",
  ],
  Activities: [
    "⚽",
    "🏀",
    "🏈",
    "⚾",
    "🎾",
    "🏐",
    "🏉",
    "🎱",
    "🏓",
    "🏸",
    "🏒",
    "🏑",
    "🏏",
    "🏹",
    "🎣",
    "🥊",
    "🥋",
    "🛹",
    "⛸️",
    "🎿",
    "🏂",
    "🏋️",
    "🤸",
    "🧘",
    "🏄",
    "🏊",
    "🎨",
    "🖌️",
    "🖍️",
    "🎭",
    "🖼️",
  ],
  Travel: [
    "🚗",
    "🚕",
    "🚙",
    "🚌",
    "🚎",
    "🏎️",
    "🚓",
    "🚑",
    "🚒",
    "🚐",
    "🚚",
    "🚛",
    "🚜",
    "🏍️",
    "🛵",
    "🚲",
    "🛴",
    "🚁",
    "✈️",
    "🛩️",
    "⛵",
    "🚤",
    "🛥️",
    "🚢",
    "⚓",
    "🚧",
    "🚦",
    "🗺️",
    "🗿",
    "🗽",
    "🗼",
    "🏰",
    "🏯",
    "🎡",
    "🎢",
    "🎠",
  ],
  Objects: [
    "⌚",
    "📱",
    "💻",
    "⌨️",
    "🖥️",
    "🖨️",
    "🖱️",
    "💽",
    "💾",
    "💿",
    "📀",
    "📅",
    "📆",
    "🗓️",
    "📇",
    "🗂️",
    "🗃️",
    "🗄️",
    "📋",
    "📊",
    "📈",
    "📉",
    "💹",
    "📁",
    "📂",
    "📄",
    "📃",
    "📑",
    "📰",
    "🗞️",
    "📓",
    "📔",
    "📒",
    "📕",
    "📗",
    "📘",
    "📙",
    "📚",
    "📖",
    "🔖",
    "🗒️",
    "📝",
    "✉️",
    "📧",
    "📨",
    "📩",
    "📤",
    "📥",
    "📦",
    "📫",
    "📪",
    "📬",
    "📭",
    "📮",
    "🗳️",
    "✏️",
    "✒️",
    "🖊️",
    "🖋️",
    "📌",
    "📍",
    "🖇️",
    "📎",
    "📏",
    "📐",
    "✂️",
    "🗑️",
    "💼",
    "📞",
    "☎️",
    "📟",
    "📠",
    "🔧",
    "🔨",
    "⚒️",
    "🛠️",
    "⚙️",
    "🔩",
    "🔋",
    "🔌",
    "💡",
    "🔦",
    "🕯️",
    "🪔",
    "💵",
    "💴",
    "💶",
    "💷",
    "💰",
    "💳",
    "💸",
    "🏦",
    "🎯",
    "🎲",
    "🧮",
    "🧾",
    "🖼️",
    "🎨",
    "🖌️",
    "🖍️",
    "🎭",
    "📷",
    "📸",
    "📹",
    "🎥",
    "📺",
    "📻",
    "🎙️",
    "🎤",
    "🎧",
    "⏰",
    "⌛",
    "⏳",
    "🗿",
  ],
}

export function EmojiPicker({ value, onChange, inline = false }: EmojiPickerProps) {
  const [searchTerm, setSearchTerm] = useState("")
  const [activeTab, setActiveTab] = useState("Smileys")
  const [open, setOpen] = useState(false)

  const allEmojis = Object.values(EMOJI_CATEGORIES).flat()

  const filteredEmojis = searchTerm
    ? allEmojis.filter((emoji) => {
        const searchLower = searchTerm.toLowerCase()
        const emojiName = EMOJI_NAMES[emoji] || ""
        return emoji.includes(searchTerm) || emojiName.toLowerCase().includes(searchLower)
      })
    : EMOJI_CATEGORIES[activeTab as keyof typeof EMOJI_CATEGORIES] || []

  const handleEmojiSelect = (emoji: string) => {
    onChange(emoji)
    setOpen(false)
  }

  if (inline) {
    return (
      <div className="space-y-2 w-full">
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" className="w-10 h-10 p-0 text-xl cursor-pointer hover:bg-muted border">
            {value || "😀"}
          </Button>
          <div className="grid grid-cols-6 gap-1 flex-1">
            {EMOJI_CATEGORIES.Smileys.slice(0, 6).map((emoji) => (
              <Button
                key={emoji}
                variant="ghost"
                size="sm"
                className="w-8 h-8 p-0 text-lg hover:bg-muted cursor-pointer"
                onClick={() => handleEmojiSelect(emoji)}
              >
                {emoji}
              </Button>
            ))}
          </div>
        </div>
        <div className="grid grid-cols-8 gap-1">
          {EMOJI_CATEGORIES.Objects.slice(0, 16).map((emoji) => (
            <Button
              key={emoji}
              variant="ghost"
              size="sm"
              className="w-8 h-8 p-0 text-lg hover:bg-muted cursor-pointer"
              onClick={() => handleEmojiSelect(emoji)}
            >
              {emoji}
            </Button>
          ))}
        </div>
      </div>
    )
  }

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger className="w-8 h-8 p-0 text-lg cursor-pointer hover:bg-muted inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 hover:bg-accent hover:text-accent-foreground">
        {value || "😀"}
      </PopoverTrigger>
      <PopoverContent
        className="w-96 p-3 z-50"
        side="bottom"
        align="start"
        sideOffset={8}
        collisionPadding={10}
        avoidCollisions={true}
        sticky="always"
        onCloseAutoFocus={(e) => e.preventDefault()}
      >
        <div className="space-y-3">
          <div className="relative">
            <Search className="w-4 h-4 absolute left-2 top-1/2 transform -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder="Search emojis..."
              className="pl-8 h-8"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>

          {!searchTerm ? (
            <Tabs value={activeTab} onValueChange={setActiveTab}>
              <TabsList className="grid w-full grid-cols-4">
                <TabsTrigger value="Smileys" className="text-xs cursor-pointer">
                  😀
                </TabsTrigger>
                <TabsTrigger value="People" className="text-xs cursor-pointer">
                  👤
                </TabsTrigger>
                <TabsTrigger value="Animals" className="text-xs cursor-pointer">
                  🐶
                </TabsTrigger>
                <TabsTrigger value="Food" className="text-xs cursor-pointer">
                  🍎
                </TabsTrigger>
              </TabsList>
              <TabsList className="grid w-full grid-cols-4 mt-1">
                <TabsTrigger value="Activities" className="text-xs cursor-pointer">
                  ⚽
                </TabsTrigger>
                <TabsTrigger value="Travel" className="text-xs cursor-pointer">
                  🚗
                </TabsTrigger>
                <TabsTrigger value="Objects" className="text-xs cursor-pointer">
                  💻
                </TabsTrigger>
                <TabsTrigger value="Symbols" className="text-xs cursor-pointer">
                  ❤️
                </TabsTrigger>
              </TabsList>

              {Object.entries(EMOJI_CATEGORIES).map(([category, emojis]) => (
                <TabsContent key={category} value={category} className="mt-2">
                  <div className="grid grid-cols-8 gap-1 max-h-48 overflow-y-auto">
                    {emojis.map((emoji) => (
                      <Button
                        key={emoji}
                        variant="ghost"
                        size="sm"
                        className="w-8 h-8 p-0 text-lg hover:bg-muted cursor-pointer"
                        onClick={() => handleEmojiSelect(emoji)}
                      >
                        {emoji}
                      </Button>
                    ))}
                  </div>
                </TabsContent>
              ))}
            </Tabs>
          ) : (
            <div className="grid grid-cols-8 gap-1 max-h-48 overflow-y-auto">
              {filteredEmojis.length > 0 ? (
                filteredEmojis.map((emoji) => (
                  <Button
                    key={emoji}
                    variant="ghost"
                    size="sm"
                    className="w-8 h-8 p-0 text-lg hover:bg-muted cursor-pointer"
                    onClick={() => handleEmojiSelect(emoji)}
                  >
                    {emoji}
                  </Button>
                ))
              ) : (
                <div className="col-span-8 text-center text-sm text-muted-foreground py-4">No emojis found</div>
              )}
            </div>
          )}
        </div>
      </PopoverContent>
    </Popover>
  )
}
